Support terraform.tfsate file missing when looking for bastion hostname
uyuni-project/terracumber pull request #20
Opened 2023-03-23 00:41 UTC by maximenoel8

When deploying an environment on AWS, we need a bastion. 

There are currently two solutions to that : 
- specify the bastion hostname during terracumber call
- look for this hostname in terraform.tfstate

In my situation, I'm creating a new AWS project where I don't specify the bastion hostname.
Because it's a new project, terraform.tfstate is not present yet.
There is already a try catch exception if bastion hostname value is not set in terraform.tfstate but we don't have this catch if terraform.tfstate file is missing.

This PR is adding this new exception.

2023-03-23 06:03 UTC, mcalmer approved these changes

2023-03-23 09:42 UTC, juliogonzalez requested changes
One small fix for the style, and one question.

2023-03-23 09:42 UTC, juliogonzalez commented on terracumber-cli
> +    except (KeyError, FileNotFoundError)as error:
```suggestion
    except (KeyError, FileNotFoundError) as error:
```

2023-03-23 09:42 UTC, juliogonzalez commented on terracumber-cli
> +    except (KeyError, FileNotFoundError)as error:
Are we sure we want to print the error for `KeyError` as well?

2023-03-27 20:55 UTC, maximenoel8 commented
KeyError cover the situation where bastion is missing from terraform.tfstate. So I think we should cover it.

2023-03-27 23:14 UTC, juliogonzalez approved these changes

2023-03-27 23:14 UTC, merged

2023-03-27 23:14 UTC, juliogonzalez commented
Thanks for the explanation. LGTM and merged.