Add option to not upload custom repositories to controller when using…
uyuni-project/terracumber pull request #3
Opened 2021-11-26 01:33 UTC by maximenoel8

## What does this PR change?

The way terracumber-cli handle customize repositories option is currently not compatible with AWS. Indeed to connect the controller, we need to use the bastion.

This first PR is to disable the push of custom repositories file to controller for AWS. 

Currently, I'm using terracucumber-cli to deploy SUMA 4.2 with MU on server without using controller. 
`cucumber_put` is not compatible with AWS yet.

2021-11-26 09:04 UTC, juliogonzalez reviewed
> Currently, I'm using terracucumber-cli to deploy SUMA 4.2 with MU on server without using controller. cucumber_put is not compatible with AWS yet.

Strictly speaking this is not about being compatible with AWS, but about being compatible with bastion hosts. It would fail outside AWS as well, unless I am missing something.

My question here is: why do we need this change? You could change the pipeline not to pass the parameter for `custom-repositories`, until we fix terracumber to be compatible with bastion hosts, right? That should avoid uploading custom repositories.

2021-11-29 07:18 UTC, maximenoel8 commented
I already changed my pipeline to be compatible with terracumber so I would like to keep it like that.

I added the bastion support for AWS. Tell me what you think ? @juliogonzalez

2021-11-29 09:33 UTC, juliogonzalez requested changes
Looks good in general. I left some comments to make it more generic, as well as some questions.

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +                        default="/home/jenkins/.ssh/testing-suma.pem",
```suggestion
                        default="~/.ssh/testing-suma.pem",
```
If I am not wrong, you will need ti expand `~`. I suggest doing it at the `parse_args` function, before returning.

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +    parser.add_argument('--bastion_key', help="""bastion key to be use""",
```suggestion
    parser.add_argument('--bastion_ssh_key', help="""bastion key to be use""",
```

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +    if args.sumaform_backend == 'aws' and (args.runstep == 'cucumber' or args.custom_repositories):
Let's not make the bastion related to the backend being used. It should work as well if we add Azure tomorrow. And it should work if for whatever reason we don't use a bastion.

I'd suggest you check if `get_bastion_hostname` is returning `None` when the bastion does not exist, and if so you check here if it's needed or not.

You will also need to run when `args.runall` is true.

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +    ctl_creds['hostname'] = ctl
As car as I can tell, you are not using `ctl` later, so you should be able to do:
```suggestion
    ctl_creds['hostname'] = get_controller_hostname(args, tf_vars)
```

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +    bst_creds['hostname'] = bst
Same as before

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +    dest_addr = (ctl_creds["hostname"], 22)  # edited#
What does the comment mean?

2021-11-29 09:33 UTC, juliogonzalez commented on terracumber-cli
> +    local_addr = (bst_creds["hostname"], 22)  # edited#
Same.

2021-11-30 05:49 UTC, maximenoel8 commented
Thanks for the review.
I updated with comments. Tell me if it's better @juliogonzalez.

2021-11-30 09:00 UTC, juliogonzalez requested changes
Looks good! Just one minor change, and I'd say we are ready to go.

What does it mean "Add support to nested cucumber"? This is about adding support for a bastion host, right?

2021-11-30 09:00 UTC, juliogonzalez commented on terracumber-cli
> +                        default="~/.ssh/testing-suma.pem",
Did you check  if `~` is understood by `bastion.connect`? Not sure if you need to expand it or not.

2021-11-30 09:00 UTC, juliogonzalez commented on terracumber-cli
> +    if get_bastion_hostname(args, tf_vars) is not None and (
You can make this shorter. If bastion is not None, then it's true:

```suggestion
    if get_bastion_hostname(args, tf_vars) and (
```

2021-11-30 09:00 UTC, juliogonzalez commented on terracumber-cli
> +    bastion_channel = bastion_transport.open_channel("direct-tcpip", (ctl_creds["hostname"], 22),
At some point later we should probably make the port for the controller, and the port for the bastion configurable, but it's OK for now.

2021-11-30 09:00 UTC, juliogonzalez commented on terracumber-cli
> +                 'port': 22, 'password': 'linux', 'sock': None}
Just curious, why do we need this?

2021-11-30 09:10 UTC, maximenoel8 commented on terracumber-cli
> +                 'port': 22, 'password': 'linux', 'sock': None}
It's the variable I use then to set my bastion port forward. You can see at lane 352 that I change it for the channel  created before.

2021-11-30 09:12 UTC, maximenoel8 commented on terracumber-cli
> +                        default="~/.ssh/testing-suma.pem",
No it was failing. I set the full path in my pipeline. I can completely remove the default value to have no mention of jenkins env.

2021-11-30 09:15 UTC, maximenoel8 commented
> Looks good! Just one minor change, and I'd say we are ready to go.
> 
> What does it mean "Add support to nested cucumber"? This is about adding support for a bastion host, right?

On AWS, controller is deployed on private network so it's not possible to reach it directly. So I call it nested but yes it's to support the bastion.

2021-12-01 19:32 UTC, maximenoel8 commented
@juliogonzalez Tell me if the last changes are enough and if I can merge the PR. 

Thanks for your help.

2021-12-02 09:19 UTC, juliogonzalez approved these changes
Argh, I am sorry. I wrote this yesterday, but didn't submit the review. If you can fix this, we are ready to merge (also please change the PR topic, this is not about nested controllers, but about using a bastion)

2021-12-02 09:19 UTC, juliogonzalez commented on terracumber-cli
> +                        )
If you removed the default value, you can move this to line 84. I don't remember how `argparse` behaves, but I guess that this `args.bastion_ssh_key` will be `None` if the key is not specified, so lines 332/333 won't fail, right?

2021-12-03 04:38 UTC, maximenoel8 commented
@juliogonzalez I added a error raise if bastion ssh key is missing. I can not merge this PR could you me the rights or do it yourself please ?

2021-12-03 11:08 UTC, juliogonzalez approved these changes
Looks good, but let's not merge today, just in case we break all the other testsuites for the whole weekend.

I am going to give you rights, and you can **coordinate** with the RRTG and merge on Monday, so if this breaks testsuites, you can quickly rollback.

2021-12-06 02:07 UTC, merged